'use client';

import { useState, useEffect } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import AssessmentUserPreference from '@/components/AssessmentUserPreference';
import Link from 'next/link';

export default function QuizPage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const [assessmentId, setAssessmentId] = useState<string | null>(null);

  const blogId = searchParams.get('blogId');
  const chapterTopicId = searchParams.get('chapterTopicId');
  const courseId = searchParams.get('courseId');

  const handleAssessmentCreated = (id: string) => {
    setAssessmentId(id);
    // Redirect to assessment page
    if (blogId) {
      // Get the blog slug from the URL or pass it as a parameter
      const slug = searchParams.get('slug') || searchParams.get('blogSlug');
      if (slug) {
        router.push(`/blogs/${slug}/assessment`);
      }
    } else if (chapterTopicId) {
      router.push(`/courses/${courseId}/assessment`);
    } else if (courseId) {
      router.push(`/courses/${courseId}/assessment`);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-blue-50/30 to-purple-50/30">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <Link 
            href={blogId ? `/blogs/${searchParams.get('slug')}?chapter=${chapterTopicId}` : '/blogs'}
            className="text-blue-600 hover:text-blue-800 transition-colors duration-200 mb-4 inline-block"
          >
            ← Back to {blogId ? 'Blog' : 'Blogs'}
          </Link>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">AI-Powered Quiz</h1>
          <p className="text-gray-600">
            Test your knowledge with personalized questions generated by AI
          </p>
        </div>

        {/* Quiz Setup */}
        <AssessmentUserPreference
          blogId={blogId || undefined}
          chapterTopicId={chapterTopicId || undefined}
          courseId={courseId || undefined}
          onAssessmentCreated={handleAssessmentCreated}
        />

        {/* Features Section */}
        <div className="mt-8 bg-white rounded-lg shadow-lg p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Quiz Features</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="flex items-start space-x-3">
              <div className="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center flex-shrink-0">
                <svg className="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
              </div>
              <div>
                <h4 className="font-medium text-gray-900">AI-Generated Questions</h4>
                <p className="text-sm text-gray-600">Questions tailored to your content and difficulty level</p>
              </div>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center flex-shrink-0">
                <svg className="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
              </div>
              <div>
                <h4 className="font-medium text-gray-900">Instant Feedback</h4>
                <p className="text-sm text-gray-600">Get immediate explanations for each answer</p>
              </div>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-8 h-8 bg-purple-100 rounded-full flex items-center justify-center flex-shrink-0">
                <svg className="w-4 h-4 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
              </div>
              <div>
                <h4 className="font-medium text-gray-900">Progress Tracking</h4>
                <p className="text-sm text-gray-600">Monitor your learning progress over time</p>
              </div>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-8 h-8 bg-orange-100 rounded-full flex items-center justify-center flex-shrink-0">
                <svg className="w-4 h-4 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 100 4m0-4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 100 4m0-4v2m0-6V4" />
                </svg>
              </div>
              <div>
                <h4 className="font-medium text-gray-900">Customizable</h4>
                <p className="text-sm text-gray-600">Choose difficulty, question types, and quantity</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
